import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import Link from "next/link";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <div
            style={{
              justifyContent: "center",
              display: "flex",
              backgroundColor: "rgba(1, 65, 255, 0.2)",
            }}
          >
            <div>
              <ul>
                <li className={styles.card}>
                  <Link href="/">Home</Link>
                </li>
                <li className={styles.card}>
                  <Link href="/typescript-types"> Types</Link>
                </li>
                <li className={styles.card}>
                  <Link href="/event-function">Event Function</Link>
                </li>
                <li className={styles.card}>
                  <Link href="/utility-types">Utility Types</Link>
                </li>
              </ul>
            </div>
          </div>
          {children}
        </body>
      </html>
    </>
  );
}
